name: Deploy to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://wsu-mens-rugby-website --delete --exclude ".git/*" --exclude ".github/*"
          # If using a build directory, replace "." with your build directory
          # Example: aws s3 sync ./build s3://wsu-mens-rugby-website --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E3D9XCSIBE030X --paths "/*"